FROM python:3.11-slim-bullseye

RUN apt-get update && apt-get upgrade -y

COPY requirements.txt /tmp/requirements.txt
RUN pip install -r /tmp/requirements.txt

COPY . /app

WORKDIR /app
EXPOSE 8000
CMD [ "python", "app.py" ]